cogs:
  - courageous_comets.cogs.about
  - courageous_comets.cogs.keywords
  - courageous_comets.cogs.interactions
  - courageous_comets.cogs.messages
  - courageous_comets.cogs.ping
  - courageous_comets.cogs.sentiment
dev-cogs:
  - jishaku
nltk:
  - punkt
  - stopwords
  - vader_lexicon
transformers:
  - sentence-transformers/all-MiniLM-L6-v2
