cogs:
  - courageous_comets.cogs.about
  - courageous_comets.cogs.messages
  - courageous_comets.cogs.ping
dev-cogs:
  - jishaku
nltk:
  - punkt
  - stopwords
  - vader_lexicon
transformers:
  - sentence-transformers/all-MiniLM-L6-v2
